#!/usr/bin/env python3
"""Export generated Shanghai Metro app data into a miniprogram JS module."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def js_dump(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def export(input_root: Path, output_path: Path) -> None:
    station_detail_map = load_json(input_root / "station_detail_map.json")
    browse_data = load_json(input_root / "browse_data.json")
    route_search_index = load_json(input_root / "route_search_index.json")
    station_search_index = load_json(input_root / "station_search_index.json")

    legend_items = [
        {"key": "inside_toilet", "label": "费区内卫生间", "color": "inside", "type": "toilet"},
        {"key": "inside_accessible", "label": "费区内无障碍卫生间", "color": "inside", "type": "accessible"},
        {"key": "outside_toilet", "label": "费区外卫生间", "color": "outside", "type": "toilet"},
        {"key": "outside_accessible", "label": "费区外无障碍卫生间", "color": "outside", "type": "accessible"},
        {"key": "inside_outside_toilet", "label": "费区内外均有卫生间", "color": "both", "type": "toilet"},
        {"key": "inside_outside_accessible", "label": "费区内外均有无障碍卫生间", "color": "both", "type": "accessible"},
    ]

    content = "\n".join(
        [
            "const legendItems = " + js_dump(legend_items),
            "",
            "const stationDetailMap = " + js_dump(station_detail_map),
            "",
            "const browseData = " + js_dump(browse_data),
            "",
            "const routeSearchIndex = " + js_dump(route_search_index),
            "",
            "const stationSearchIndex = " + js_dump(station_search_index),
            "",
            "module.exports = {",
            "  legendItems,",
            "  stationDetailMap,",
            "  browseData,",
            "  routeSearchIndex,",
            "  stationSearchIndex,",
            "}",
            "",
        ]
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export Shanghai Metro app data into a miniprogram JS module."
    )
    parser.add_argument(
        "--input-root",
        default="output/shmetro/app",
        help="Directory generated by shmetro_prepare_app_data.py",
    )
    parser.add_argument(
        "--output",
        default="miniprogram/data/shmetro-data.js",
        help="Output JS module path",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        export(Path(args.input_root), Path(args.output))
    except Exception as exc:  # pragma: no cover
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
