#!/usr/bin/env python3
"""Export generated Shanghai Metro app data into miniprogram JS data modules."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_js_module(path: Path, variable_name: str, payload: Any) -> None:
    path.write_text(
        f"const {variable_name} = {json.dumps(payload, ensure_ascii=False, indent=2)}\n\n"
        f"module.exports = {variable_name}\n",
        encoding="utf-8",
    )


def export(input_root: Path, output_root: Path) -> None:
    station_detail_map = load_json(input_root / "station_detail_map.json")
    browse_data = load_json(input_root / "browse_data.json")
    route_search_index = load_json(input_root / "route_search_index.json")
    station_search_index = load_json(input_root / "station_search_index.json")

    legend_items = [
        {"key": "inside_toilet", "label": "费区内卫生间", "color": "inside", "type": "toilet"},
        {"key": "inside_accessible", "label": "费区内无障碍卫生间", "color": "inside", "type": "accessible"},
        {"key": "outside_toilet", "label": "费区外卫生间", "color": "outside", "type": "toilet"},
        {"key": "outside_accessible", "label": "费区外无障碍卫生间", "color": "outside", "type": "accessible"},
        {"key": "inside_outside_toilet", "label": "费区内外均有卫生间", "color": "both", "type": "toilet"},
        {"key": "inside_outside_accessible", "label": "费区内外均有无障碍卫生间", "color": "both", "type": "accessible"},
    ]

    raw_station_to_entity = {}
    for entity_id, detail in station_detail_map.items():
        for raw_station_id in detail.get("raw_station_ids", []):
            raw_station_to_entity[raw_station_id] = entity_id

    output_root.mkdir(parents=True, exist_ok=True)
    write_js_module(output_root / "legend-items.js", "legendItems", legend_items)
    write_js_module(output_root / "station-detail-map.js", "stationDetailMap", station_detail_map)
    write_js_module(output_root / "raw-station-to-entity.js", "rawStationToEntity", raw_station_to_entity)
    write_js_module(output_root / "browse-data.js", "browseData", browse_data)
    write_js_module(output_root / "route-search-index.js", "routeSearchIndex", route_search_index)
    write_js_module(output_root / "station-search-index.js", "stationSearchIndex", station_search_index)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export Shanghai Metro app data into a miniprogram JS module."
    )
    parser.add_argument(
        "--input-root",
        default="output/shmetro/app",
        help="Directory generated by shmetro_prepare_app_data.py",
    )
    parser.add_argument(
        "--output-root",
        default="miniprogram/data",
        help="Output directory for JSON data files",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        export(Path(args.input_root), Path(args.output_root))
    except Exception as exc:  # pragma: no cover
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
