#!/usr/bin/env python3
"""Export generated Shanghai Metro app data into miniprogram JSON files."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def export(input_root: Path, output_root: Path) -> None:
    station_detail_map = load_json(input_root / "station_detail_map.json")
    browse_data = load_json(input_root / "browse_data.json")
    route_search_index = load_json(input_root / "route_search_index.json")
    station_search_index = load_json(input_root / "station_search_index.json")

    legend_items = [
        {"key": "inside_toilet", "label": "费区内卫生间", "color": "inside", "type": "toilet"},
        {"key": "inside_accessible", "label": "费区内无障碍卫生间", "color": "inside", "type": "accessible"},
        {"key": "outside_toilet", "label": "费区外卫生间", "color": "outside", "type": "toilet"},
        {"key": "outside_accessible", "label": "费区外无障碍卫生间", "color": "outside", "type": "accessible"},
        {"key": "inside_outside_toilet", "label": "费区内外均有卫生间", "color": "both", "type": "toilet"},
        {"key": "inside_outside_accessible", "label": "费区内外均有无障碍卫生间", "color": "both", "type": "accessible"},
    ]

    raw_station_to_entity = {}
    for entity_id, detail in station_detail_map.items():
        for raw_station_id in detail.get("raw_station_ids", []):
            raw_station_to_entity[raw_station_id] = entity_id

    output_root.mkdir(parents=True, exist_ok=True)
    (output_root / "legend-items.json").write_text(
        json.dumps(legend_items, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (output_root / "station-detail-map.json").write_text(
        json.dumps(station_detail_map, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (output_root / "raw-station-to-entity.json").write_text(
        json.dumps(raw_station_to_entity, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (output_root / "browse-data.json").write_text(
        json.dumps(browse_data, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (output_root / "route-search-index.json").write_text(
        json.dumps(route_search_index, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (output_root / "station-search-index.json").write_text(
        json.dumps(station_search_index, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export Shanghai Metro app data into a miniprogram JS module."
    )
    parser.add_argument(
        "--input-root",
        default="output/shmetro/app",
        help="Directory generated by shmetro_prepare_app_data.py",
    )
    parser.add_argument(
        "--output-root",
        default="miniprogram/data",
        help="Output directory for JSON data files",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        export(Path(args.input_root), Path(args.output_root))
    except Exception as exc:  # pragma: no cover
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
